RudakBlogBundle_admin_blog_tag:
    resource: "@RudakBlogBundle/Resources/config/routing/tag.yml"
    prefix:   /tag

RudakBlogBundle_admin_blog_category:
    resource: "@RudakBlogBundle/Resources/config/routing/category.yml"
    prefix:   /category

RudakBlogBundle_admin_blog_post:
    resource: "@RudakBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

RudakBlogBundle_admin_blog_comment:
    resource: "@RudakBlogBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
