admin_blog_category:
    path:     /
    defaults: { _controller: "RudakBlogBundle:Category:index" }

admin_blog_category_show:
    path:     /{id}/show
    defaults: { _controller: "RudakBlogBundle:Category:show" }

admin_blog_category_new:
    path:     /new
    defaults: { _controller: "RudakBlogBundle:Category:new" }

admin_blog_category_create:
    path:     /create
    defaults: { _controller: "RudakBlogBundle:Category:create" }
    requirements: { _method: post }

admin_blog_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "RudakBlogBundle:Category:edit" }

admin_blog_category_update:
    path:     /{id}/update
    defaults: { _controller: "RudakBlogBundle:Category:update" }
    requirements: { _method: post|put }

admin_blog_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "RudakBlogBundle:Category:delete" }
    requirements: { _method: post|delete }
