admin_blog_tag:
    path:     /
    defaults: { _controller: "RudakBlogBundle:Tag:index" }

admin_blog_tag_show:
    path:     /{id}/show
    defaults: { _controller: "RudakBlogBundle:Tag:show" }

admin_blog_tag_new:
    path:     /new
    defaults: { _controller: "RudakBlogBundle:Tag:new" }

admin_blog_tag_create:
    path:     /create
    defaults: { _controller: "RudakBlogBundle:Tag:create" }
    requirements: { _method: post }

admin_blog_tag_edit:
    path:     /{id}/edit
    defaults: { _controller: "RudakBlogBundle:Tag:edit" }

admin_blog_tag_update:
    path:     /{id}/update
    defaults: { _controller: "RudakBlogBundle:Tag:update" }
    requirements: { _method: post|put }

admin_blog_tag_delete:
    path:     /{id}/delete
    defaults: { _controller: "RudakBlogBundle:Tag:delete" }
    requirements: { _method: post|delete }
